title: Livia Moreira
logo: /assets/img/Livia_Moreira_ProfilePic3.jpg
description: Meet Livia, a seasoned Data Analyst with over 10 years of experience across diverse industries, specializing in People Analytics. With a Bachelor's in Business and a Master's in Data Management and Analytics, Livia leverages her strong analytical skills to uncover valuable insights from complex data set
#show_downloads: true
theme: jekyll-theme-minimal
